[package]
name = "async-pos-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
leveldb = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
tokio = { version = "1.38", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
rand = "0.8"
sha2 = "0.10"
chrono = "0.4"
db-key = "0.0.5"
rocksdb = "0.21"